USE [CTRL_ORCAMENTO_HMG]
GO

/****** Object:  Table [dbo].[AGENCIA]    Script Date: 09/19/2018 20:51:28 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AGENCIA]') AND type in (N'U'))
DROP TABLE [dbo].[AGENCIA]
GO

USE [CTRL_ORCAMENTO_HMG]
GO

/****** Object:  Table [dbo].[AGENCIA]    Script Date: 09/19/2018 20:51:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AGENCIA](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BANCO_ID] [bigint] NOT NULL,
	[NUMERO] [varchar](5) NOT NULL,
	[DV] [varchar](1) NOT NULL,
	
	[USUARIO_INCLUSAO] [bigint] NULL,
	[DATA_INCLUSAO] [datetime] NOT NULL,
	
	[USUARIO_ALTERACAO] [bigint] NULL,
	[DATA_ALTERACAO] [datetime] NULL,
	
	[USUARIO_CANCELAMENTO] [bigint] NULL,
	[DATA_CANCELAMENTO] [datetime] NULL,
	
 CONSTRAINT [PK_AGENCIA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],

UNIQUE NONCLUSTERED 
(
	[USUARIO_INCLUSAO], [BANCO_ID], [NUMERO] ASC
)

) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


