USE [CTRL_ORCAMENTO_HMG]
GO

/****** Object:  Table [dbo].[BANCO]    Script Date: 09/19/2018 17:29:04 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BANCO]') AND type in (N'U'))
DROP TABLE [dbo].[BANCO]
GO

USE [CTRL_ORCAMENTO_HMG]
GO

/****** Object:  Table [dbo].[BANCO]    Script Date: 09/19/2018 17:29:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BANCO](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODIGO] [varchar](10) NOT NULL,
	[NOME] [varchar](100) NOT NULL,
	
	[USUARIO_INCLUSAO] [bigint] NULL,
	[DATA_INCLUSAO] [date] NOT NULL,
	
	[USUARIO_ALTERACAO] [bigint] NULL,
	[DATA_ALTERACAO] [date] NULL,
	
	[USUARIO_CANCELAMENTO] [bigint] NULL,
	[DATA_CANCELAMENTO] [date] NULL,
	
UNIQUE NONCLUSTERED 
(
	[CODIGO] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] 

GO


