USE [CTRL_ORCAMENTO_HMG]
GO

/****** Object:  Table [dbo].[USUARIO]    Script Date: 09/19/2018 17:29:35 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USUARIO]') AND type in (N'U'))
DROP TABLE [dbo].[USUARIO]
GO

USE [CTRL_ORCAMENTO_HMG]
GO

/****** Object:  Table [dbo].[USUARIO]    Script Date: 09/19/2018 17:29:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[USUARIO](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](50) NULL,
	[SOBRENOME] [varchar](100) NULL,
	[EMAIL] [varchar](254) NOT NULL,
	[LOGIN] [varchar](254) NOT NULL,
	[SENHA] [varchar](max) NOT NULL,
	[CLAIM] [varchar](20) NULL,
	
	[DATA_VERIFICACAO] [date] NULL,
	[VERIFICADO] [bit] NULL,
	
	[SALT] [varchar](max) NOT NULL,
	
	[BLOQUEADO] [bit] NULL,
	[DATA_BLOQUEIO] [date] NULL,
	[USUARIO_BLOQUEIO] [bigint] NULL,
	
	[USUARIO_INCLUSAO] [bigint] NULL,
	[DATA_INCLUSAO] [date] NOT NULL,
	
	[USUARIO_ALTERACAO] [bigint] NULL,
	[DATA_ALTERACAO] [date] NULL,
	
	[USUARIO_CANCELAMENTO] [bigint] NULL,
	[DATA_CANCELAMENTO] [date] NULL,
UNIQUE NONCLUSTERED 
(
	[LOGIN] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


